/*
 * This source file was generated by the Gradle 'init' task
 */
package WeekSwing;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;

public class App extends JFrame {
    public App() {
        setLayout(new BorderLayout());
        setTitle("Week Swing");
        setSize(920, 280);
        setResizable(true);

JScrollPane scrollPane = new JScrollPane(new Griddy());
scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
scrollPane.getVerticalScrollBar().setUnitIncrement(17);

JSplitPane splitPane = new JSplitPane();
splitPane.setDividerLocation(240);
splitPane.setDividerSize(4);
splitPane.setLeftComponent(new SideBar());
splitPane.setRightComponent(scrollPane);

        

        add(splitPane);

        // Create a panel for the top layout
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new BoxLayout(topPanel, BoxLayout.X_AXIS)); // Horizontal layout
        topPanel.setBackground(Color.GRAY);
        topPanel.add(Box.createHorizontalStrut(10)); // Add spacing

        JLabel characters = new JLabel("Power Tier Characters Anime");
        characters.setForeground(Color.WHITE);
        characters.setPreferredSize(new Dimension(1900, 40));
        characters.setBackground(Color.GRAY);
        topPanel.add(characters);


        Discord discord = new Discord("Discord");
        topPanel.add(discord);

        Kofi kofi = new Kofi("Buy me a Ko-Fi!");
        topPanel.add(Box.createHorizontalStrut(10)); // Add spacing
        topPanel.add(kofi);

        add(topPanel, BorderLayout.NORTH);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    public static void main(String[] args) {
        new App();
    }
}
